disabled_rules: # rule identifiers to exclude from running
  - identifier_name
#   - comma
#   - control_statement
# opt_in_rules: # some rules are only opt-in
#   - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - CachAR
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try: warning # explicitly
shorthand_operator: warning
# rules that have both warning and error levels, can set just the warning level
# implicitly
# identifier_name:
#   allowed_symbols: "_"
#   min_length: 2
#   max_length:
#     warning: 90
#     error: 1000
line_length:
  warning: 110
  error: 310

function_body_length:
  warning: 100
  error: 500

type_body_length:
  warning: 500
  error: 1000

large_tuple:
  warning: 2
  error: 5
# they can set both implicitly with an array
# or they can set both explicitly
file_length:
  warning: 500
  error: 1500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
# identifier_name:
#   min_length: # only min_length
#     error: 4 # only error
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
